#!/bin/bash
if [ $# -lt 1 ]
then
	echo Usage: $0 CMD [ARGS]
else
	executable=$1
	shift
	( xdotool search --sync --onlyvisible --pid $$ 2> /dev/null | xargs -I {} xdotool windowsize {} 100% 100% ) &
	exec $executable "$@"
fi
